apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - gitlab-registry-credentials.yaml

patches:
  - target:
      kind: Ingress
      name: metabotnik-api
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: metabotnik.platforms-test.cloud.brill.com
