apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metabotnik

commonAnnotations:
  repository: https://gitlab.com/brillpublishers/code/metabotnik.git

transformers:
  - labels.yaml

resources:
  - metabotnik.yaml

images:
  - name: registry.gitlab.com/brillpublishers/code/metabotnik
    newTag: latest  ## this is the "latest" tag in the build process